### ISSUE TITLE
why we select these numbers?image_embeddings = [image_features[0], image_features[2][4], image_features[2][8], image_features[2][12], image_features[2][16]]

### ISSUE THREAD

**Issue by zhangtao22** [csyxwei/ELITE#10]
In either global or local, you all have this. What do these vectors represent?why we select [image_features[0], image_features[2][4], image_features[2][8], image_features[2][12], image_features[2][16]] (看了你讲的视频，里面没说清楚啊？请教能不能详细说一下，谢谢)

**Comment by csyxwei** [comment]
Hi,

- `[image_features[0], image_features[2][4], image_features[2][8], image_features[2][12], image_features[2][16]]` are the features from the different layers of CLIP image encoder. `image_features[0]` is the last layer feature and others are intermediate layer features.

- As stated in Sec 3.2, we use the features from multiple layers to learn multiple words so that we can obtain a well-editable primary word. Except for the last layer, the index of the middle layer was selected empirically.
