### ISSUE TITLE
Where did you add the placeholder token as a additional special token in the tokenizer  ？I haven't seen it，：）

### ISSUE THREAD

**Issue by wangzhaolei** [csyxwei/ELITE#8]

**Comment by csyxwei** [comment]
Hi, 

Instead of adding a new placeholder directly, we rewrite the forward function of the text encoder to inject the obtained word embedding.

You can refer to [inj_forward_text](https://github.com/csyxwei/ELITE/blob/0e87d9c9c06a2a1fa0f151d6ef9975f3b456b646/train_global.py#L83) for details.

**Comment by wangzhaolei** [comment]
Thanks for you answering so quickly！I get it ！

By the way, why not use the tokenizer and text encoder in the stabel diffusion v1.4 pre-training model, but use the tokenizer and text encoder in models--openai--clip-vit-large-patch14?      Thankyou

**Comment by csyxwei** [comment]
For me, I loaded the tokenizer and text encoder from the `stable diffusion v1.4` failed (maybe caused by the diffusers version), so I used the `models--openai--clip-vit-large-patch14` instead. The tokenizer and text encoder from `sd` and `clip` should be the same. So you can also use them provided by sd v1.4, which is recommended, haha.

**Comment by wangzhaolei** [comment]
Ok, models--openai--clip-vit-large-patch14 works well.  Your job is amazing!  Thank you so much, haha :)
